// Comprehensive faculties and departments database organized by institution type/category
// Users can search faculties and then departments within their institution

export const FACULTIES_BY_INSTITUTION: Record<string, string[]> = {
  // ─── FEDERAL UNIVERSITIES ───
  'University of Lagos (UNILAG), Lagos': [
    'Faculty of Administration',
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Basic Medical Sciences',
    'Faculty of Clinical Sciences',
    'Faculty of Dentistry',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Environmental Design',
    'Faculty of Law',
    'Faculty of Pharmacy',
    'Faculty of Science',
    'Faculty of Social Sciences',
    'Faculty of Technology',
  ],
  'University of Ibadan (UI)': [
    'Faculty of Administration',
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Basic Medical Sciences',
    'Faculty of Clinical Sciences',
    'Faculty of Dentistry',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Pharmacy',
    'Faculty of Science',
    'Faculty of Social Sciences',
    'Faculty of Technology',
    'Faculty of Veterinary Medicine',
  ],
  'University of Nigeria, Nsukka (UNN)': [
    'Faculty of Biological Sciences',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Environmental Sciences',
    'Faculty of Law',
    'Faculty of Medical Sciences',
    'Faculty of Physical Sciences',
    'Faculty of Social Sciences',
    'Faculty of Agriculture',
    'Faculty of Arts',
  ],
  'Ahmadu Bello University, Zaria (ABU)': [
    'Faculty of Administration',
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Medicine',
    'Faculty of Pharmacy',
    'Faculty of Science',
    'Faculty of Social Sciences',
    'Faculty of Technology',
    'Faculty of Veterinary Medicine',
  ],
  'Bayero University, Kano (BUK)': [
    'Faculty of Administration',
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Medicine',
    'Faculty of Pharmacy',
    'Faculty of Science',
    'Faculty of Social Sciences',
    'Faculty of Technology',
  ],
  'Obafemi Awolowo University, Ile-Ife (OAU)': [
    'Faculty of Administration',
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Basic Medical Sciences',
    'Faculty of Clinical Sciences',
    'Faculty of Dentistry',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Pharmacy',
    'Faculty of Science',
    'Faculty of Social Sciences',
    'Faculty of Technology',
    'Faculty of Veterinary Medicine',
  ],
  'Federal University of Technology, Minna (FUTMINNA)': [
    'Faculty of Agriculture and Agricultural Technology',
    'Faculty of Engineering',
    'Faculty of Life Sciences',
    'Faculty of Science',
    'Faculty of Technology',
    'School of Information and Communication Technology',
  ],
  'Federal University of Technology, Akure (FUTA)': [
    'Faculty of Agriculture',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Life Sciences',
    'Faculty of Science',
    'Faculty of Technology',
  ],
  'Federal University of Technology, Owerri (FUTO)': [
    'Faculty of Agriculture',
    'Faculty of Engineering',
    'Faculty of Science',
    'Faculty of Technology',
  ],
  'Federal University of Petroleum Resources, Effurun (FUPRE)': [
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Science',
    'Faculty of Social Sciences',
  ],
  'University of Benin (UNIBEN)': [
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Medicine',
    'Faculty of Pharmacy',
    'Faculty of Science',
    'Faculty of Social Sciences',
    'Faculty of Technology',
  ],
  'Nnamdi Azikiwe University (UNIZIK), Awka': [
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Medicine',
    'Faculty of Pharmaceutical Sciences',
    'Faculty of Physical Sciences',
    'Faculty of Social Sciences',
  ],
  'Usmanu Danfodiyo University, Sokoto (UDUS)': [
    'Faculty of Administration',
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Medicine',
    'Faculty of Pharmacy',
    'Faculty of Science',
    'Faculty of Social Sciences',
  ],
  'University of Maiduguri (UNIMAID)': [
    'Faculty of Administration',
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Medicine',
    'Faculty of Science',
    'Faculty of Social Sciences',
  ],
  'University of Jos (UNIJOS)': [
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Health Sciences',
    'Faculty of Law',
    'Faculty of Natural Sciences',
    'Faculty of Social Sciences',
    'Faculty of Medicine',
  ],
  'University of Ilorin (UNILORIN)': [
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering and Technology',
    'Faculty of Law',
    'Faculty of Medicine',
    'Faculty of Science',
    'Faculty of Social Sciences',
    'Faculty of Technology',
  ],
  'University of Calabar (UNICAL)': [
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Medical Sciences',
    'Faculty of Pharmacy',
    'Faculty of Science',
    'Faculty of Social Sciences',
  ],
  'Abubakar Tafawa Balewa University (ATBU), Bauchi': [
    'Faculty of Agriculture',
    'Faculty of Arts and Social Sciences',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Medical Sciences',
    'Faculty of Science',
    'Faculty of Technology',
  ],
  'Federal University of Agriculture, Abeokuta (FUNAAB)': [
    'Faculty of Agriculture',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Science',
    'Faculty of Social Sciences',
    'Faculty of Technology',
  ],
  'Federal University of Agriculture, Makurdi (FUAM)': [
    'Faculty of Agriculture',
    'Faculty of Agro-Industrial Technology',
    'Faculty of Education',
    'Faculty of Law',
    'Faculty of Science and Science Education',
    'Faculty of Social Sciences',
  ],
  'Michael Okpara University of Agriculture, Umudike': [
    'Faculty of Agricultural Sciences',
    'Faculty of Engineering',
    'Faculty of Environmental Sciences',
    'Faculty of Pharmaceutical Sciences',
    'Faculty of Physical Sciences',
    'Faculty of Social Sciences',
  ],

  // ─── STATE UNIVERSITIES ───
  'Lagos State University (LASU), Ojo': [
    'Faculty of Administration',
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Environmental Design and Management',
    'Faculty of Law',
    'Faculty of Science',
    'Faculty of Social Sciences',
  ],
  'Enugu State University of Science & Technology (ESUT)': [
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Medical Sciences',
    'Faculty of Science',
    'Faculty of Social Sciences',
  ],
  'Osun State University, Osogbo (UNIOSUN)': [
    'Faculty of Administration',
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Science',
    'Faculty of Social Sciences',
  ],
  'Oyo State University of Science and Technology, Ibadandodo': [
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Science',
    'Faculty of Technology',
  ],
  'Ondo State University, Ondo': [
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Science',
    'Faculty of Social Sciences',
  ],
  'Abia State University (ABSU), Uturu': [
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Management Sciences',
    'Faculty of Science',
    'Faculty of Social Sciences',
  ],
  'Anambra State University, Uli': [
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Science',
    'Faculty of Social Sciences',
  ],
  'Delta State University, Abraka (DELSU)': [
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Science',
    'Faculty of Social Sciences',
  ],
  'Cross River University of Technology (CRUTECH), Calabar': [
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Science',
    'Faculty of Technology',
  ],
  'Rivers State University, Port Harcourt (RSU)': [
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Science',
    'Faculty of Social Sciences',
  ],

  // ─── PRIVATE UNIVERSITIES ───
  'Covenant University, Ota': [
    'College of Development Studies',
    'College of Engineering',
    'College of Leadership Development',
    'College of Science and Technology',
  ],
  'Babcock University, Ilishan-Remo': [
    'Faculty of Agriculture',
    'Faculty of Basic and Applied Sciences',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Health Sciences',
    'Faculty of Law',
    'Faculty of Management Studies',
    'Faculty of Social and Management Sciences',
  ],
  'Pan-Atlantic University, Ibeju-Lekki': [
    'School of Business',
    'School of Engineering and Physical Sciences',
    'School of Law',
    'School of Media and Communication',
    'School of Politics and International Relations',
  ],
  'Redeemer\'s University, Ede': [
    'Faculty of Computing and Information Technology',
    'Faculty of Education',
    'Faculty of Engineering and Technology',
    'Faculty of Environmental Sciences',
    'Faculty of Management and Social Sciences',
    'Faculty of Medicine',
    'Faculty of Natural Sciences',
  ],
  'Afe Babalola University, Ado-Ekiti (ABUAD)': [
    'Faculty of Basic and Applied Sciences',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Environmental Studies',
    'Faculty of Law',
    'Faculty of Management and Business Administration',
  ],
  'Benson Idahosa University, Benin City': [
    'Faculty of Arts',
    'Faculty of Law',
    'Faculty of Management and Social Sciences',
    'Faculty of Science',
  ],
  'Igbinedion University, Okada': [
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Medicine',
    'Faculty of Science',
    'Faculty of Social Sciences',
  ],
  'Madonna University, Okija': [
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Management Sciences',
    'Faculty of Science',
  ],
  'American University of Nigeria, Yola': [
    'School of Arts and Social Sciences',
    'School of Business and Entrepreneurship',
    'School of Engineering and Computer Science',
    'School of Education',
    'School of Health and Natural Sciences',
    'School of Law',
  ],
  'Landmark University, Omu-Aran': [
    'Faculty of Agriculture',
    'Faculty of Arts',
    'Faculty of Education',
    'Faculty of Engineering',
    'Faculty of Law',
    'Faculty of Management Sciences',
    'Faculty of Medicine',
    'Faculty of Science',
  ],
  'Caleb University, Lagos': [
    'Faculty of Arts and Social Sciences',
    'Faculty of Business and Management',
    'Faculty of Law',
    'Faculty of Science and Technology',
  ],
  'Ritman University, Ikot Ekpene': [
    'Faculty of Arts and Humanities',
    'Faculty of Law',
    'Faculty of Management Sciences',
    'Faculty of Science and Technology',
  ],
}

export const DEPARTMENTS_BY_FACULTY: Record<string, string[]> = {
  // ─── GENERAL MAPPINGS ───
  'Faculty of Administration': [
    'Public Administration',
    'Business Administration',
    'Local Government Administration',
    'Office Technology and Management',
  ],
  'Faculty of Agriculture': [
    'Agricultural Economics',
    'Agricultural Engineering',
    'Agronomy',
    'Animal Science',
    'Crop Production',
    'Fisheries and Aquaculture',
    'Horticulture',
    'Plant Pathology',
    'Soil Science',
    'Veterinary Medicine',
  ],
  'Faculty of Arts': [
    'English Language',
    'French',
    'History',
    'Philosophy',
    'Religious Studies',
    'Linguistics',
    'Literature in English',
    'Arabic',
    'Yoruba',
    'Igbo',
    'Hausa',
  ],
  'Faculty of Education': [
    'Educational Administration and Planning',
    'Educational Foundations',
    'Educational Technology',
    'Guidance and Counseling',
    'Human Kinetics and Health Education',
    'Teacher Education in Science',
    'Teacher Education in Mathematics',
    'Teacher Education in Social Sciences',
    'Early Childhood Education',
    'Curriculum Studies',
  ],
  'Faculty of Engineering': [
    'Aeronautical Engineering',
    'Agricultural Engineering',
    'Chemical Engineering',
    'Civil Engineering',
    'Electrical Engineering',
    'Electronic Engineering',
    'Environmental Engineering',
    'Geological Engineering',
    'Marine Engineering',
    'Mechanical Engineering',
    'Metallurgical Engineering',
    'Petroleum Engineering',
    'Systems Engineering',
  ],
  'Faculty of Law': [
    'Commercial Law',
    'Constitutional Law',
    'Criminal Law',
    'Family Law',
    'International Law',
    'Labour Law',
    'Land Law',
    'Property Law',
    'Taxation Law',
  ],
  'Faculty of Medicine': [
    'Medicine',
    'Surgery',
    'Pediatrics',
    'Obstetrics and Gynecology',
    'Psychiatry',
    'Radiology',
    'Anatomy',
    'Physiology',
    'Biochemistry',
    'Pathology',
    'Pharmacology',
    'Microbiology',
  ],
  'Faculty of Pharmacy': [
    'Pharmaceutics',
    'Pharmaceutical Chemistry',
    'Pharmacology and Toxicology',
    'Pharmacognosy',
    'Clinical Pharmacy',
    'Hospital Pharmacy',
  ],
  'Faculty of Science': [
    'Botany',
    'Chemistry',
    'Geology',
    'Mathematics',
    'Physics',
    'Zoology',
    'Microbiology',
    'Biochemistry',
    'Statistics',
    'Computer Science',
    'Meteorology',
  ],
  'Faculty of Social Sciences': [
    'Accounting',
    'Economics',
    'Geography',
    'Mass Communication',
    'Political Science',
    'Psychology',
    'Sociology',
    'Anthropology',
    'Social Work',
    'Library Science',
  ],
  'Faculty of Technology': [
    'Food Technology',
    'Environmental Technology',
    'Building Technology',
    'Urban and Regional Planning',
    'Surveying and Geo-informatics',
  ],
  'Faculty of Basic Medical Sciences': [
    'Anatomy',
    'Biochemistry',
    'Microbiology',
    'Pharmacology',
    'Physiology',
    'Pathology',
  ],
  'Faculty of Clinical Sciences': [
    'Medicine',
    'Surgery',
    'Pediatrics',
    'Obstetrics and Gynecology',
    'Internal Medicine',
  ],
  'Faculty of Dentistry': [
    'Preventive Dentistry',
    'Restorative Dentistry',
    'Oral and Maxillofacial Surgery',
    'Periodontology',
    'Orthodontics',
  ],
  'Faculty of Environmental Design': [
    'Architecture',
    'Urban and Regional Planning',
    'Landscape Architecture',
    'Building Technology',
  ],
  'Faculty of Environmental Sciences': [
    'Environmental Science',
    'Urban and Regional Planning',
    'Forestry',
    'Wildlife and Fisheries',
  ],
  'Faculty of Physical Sciences': [
    'Chemistry',
    'Physics',
    'Mathematics',
    'Geology',
    'Astronomy',
  ],
  'Faculty of Biological Sciences': [
    'Botany',
    'Zoology',
    'Microbiology',
    'Ecology',
    'Marine Science',
  ],

  // Default departments if specific faculty mapping not found
  'Other': [
    'Not specified',
    'Choose from faculty first',
  ],
}

// Get departments for a selected faculty
export function getDepartmentsByFaculty(faculty: string): string[] {
  return DEPARTMENTS_BY_FACULTY[faculty] || DEPARTMENTS_BY_FACULTY['Other']
}

// Get faculties for a selected institution
export function getFacultiesByInstitution(institution: string): string[] {
  return FACULTIES_BY_INSTITUTION[institution] || []
}
