export const NIGERIA_STATES = [
  'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa',
  'Benue', 'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo',
  'Ekiti', 'Enugu', 'FCT (Abuja)', 'Gombe', 'Imo', 'Jigawa',
  'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara',
  'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun',
  'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara',
] as const

export type NigeriaState = (typeof NIGERIA_STATES)[number]

export const INSTITUTIONS_BY_STATE: Record<string, string[]> = {
  Abia: [
    'Abia State University (ABSU), Uturu',
    'Michael Okpara University of Agriculture, Umudike',
    'Gregory University, Uturu',
    'Abia State Polytechnic, Aba',
    'Clifford University, Aba',
    'Federal Polytechnic, Bende',
    'Abia College of Education, Arochukwu',
    'Abia College of Education, Uturu',
  ],
  Adamawa: [
    'Modibbo Adama University, Yola',
    'Adamawa State University, Mubi',
    'American University of Nigeria, Yola',
    'Adamawa State Polytechnic, Yola',
    'Federal Polytechnic, Mubi',
    'Federal Polytechnic, Yola',
    'Adamawa State College of Education, Yola',
    'Adamawa State College of Education, Mubi',
  ],
  'Akwa Ibom': [
    'University of Uyo (UNIUYO)',
    'Akwa Ibom State University, Ikot Akpaden',
    'Ritman University, Ikot Ekpene',
    'Heritage Polytechnic, Eket',
    'Akwa Ibom State Polytechnic, Ikot Osurua',
    'Essien Udim Polytechnic',
    'Akwa Ibom State College of Education, Oron',
    'Akwa Ibom State College of Education, Esman',
  ],
  Anambra: [
    'Nnamdi Azikiwe University (UNIZIK), Awka',
    'Chukwuemeka Odumegwu Ojukwu University (COOU), Anambra',
    'Paul University, Awka',
    'Madonna University, Okija',
    'Anambra State Polytechnic, Mgbakwu',
    'Anambra State University, Uli',
    'College of Education, Nsugbe',
    'Anambra State College of Education, Awka',
  ],
  Bauchi: [
    'Abubakar Tafawa Balewa University (ATBU), Bauchi',
    'Bauchi State University, Gadau',
    'Bauchi State Polytechnic, Bauchi',
    'Federal Polytechnic, Bauchi',
    'Bauchi State University of Science and Technology',
    'Bauchi College of Education, Bauchi',
    'Bauchi College of Education, Azare',
  ],
  Bayelsa: [
    'Niger Delta University, Wilberforce Island',
    'Federal University, Otuoke',
    'Isaac Jasper Boro College of Education, Sagbama',
    'Bayelsa State Polytechnic, Aleibiri',
    'Bayelsa State University, Yenagoa',
    'Bayelsa College of Education, Sagbama',
  ],
  Benue: [
    'Joseph Sarwuan Tarka University, Makurdi (JOSTUM)',
    'Benue State University, Makurdi',
    'Federal University of Agriculture, Makurdi (FUAM)',
    'Benue State Polytechnic, Ugbokolo',
    'Federal Polytechnic, Idah',
    'Benue State Polytechnic, Makurdi',
    'Benue State College of Education, Makurdi',
    'College of Education, Katsina-Ala',
  ],
  Borno: [
    'University of Maiduguri (UNIMAID)',
    'Borno State University, Maiduguri',
    'Ramat Polytechnic, Maiduguri',
    'Federal Polytechnic, Maiduguri',
    'Borno State Polytechnic',
    'Borno State College of Education, Maiduguri',
    'Kashim Ibrahim College of Education, Maiduguri',
  ],
  'Cross River': [
    'University of Calabar (UNICAL)',
    'Cross River University of Technology (CRUTECH), Calabar',
    'Arthur Jarvis University, Akpabuyo',
    'Cross River State Polytechnic, Calabar',
    'Federal Polytechnic, Obudu',
    'Cross River University, Calabar',
    'College of Education, Calabar',
    'College of Education, Obudu',
  ],
  Delta: [
    'Delta State University, Abraka (DELSU)',
    'Federal University of Petroleum Resources, Effurun (FUPRE)',
    'University of Delta, Agbor',
    'Dennis Osadebay University, Asaba',
    'Delta State Polytechnic, Ogwashi-Uku',
    'Delta State Polytechnic, Ozoro',
    'Federal Polytechnic, Otele',
    'Federal Polytechnic, Ekowe',
    'Delta State College of Education, Asaba',
    'Delta State College of Education, Agbor',
  ],
  Ebonyi: [
    'Ebonyi State University, Abakaliki (EBSU)',
    'Alex Ekwueme Federal University, Ndufu-Alike (FUNAI)',
    'David Umahi Federal University of Health Sciences, Uburu',
    'Ebonyi State Polytechnic, Abakaliki',
    'Ebonyi State University, Abakaliki',
    'Ebonyi State College of Education, Ikwo',
  ],
  Edo: [
    'University of Benin (UNIBEN)',
    'Ambrose Alli University, Ekpoma (AAU)',
    'Benson Idahosa University, Benin City',
    'Igbinedion University, Okada',
    'Wellspring University, Benin City',
    'Edo State University, Uzairue',
    'Edo State Polytechnic, Urechie',
    'Federal Polytechnic, Auchi',
    'College of Education, Benin City',
    'Edo College of Education, Igueben',
  ],
  Ekiti: [
    'Ekiti State University (EKSU), Ado-Ekiti',
    'Federal University Oye-Ekiti (FUOYE)',
    'Afe Babalola University, Ado-Ekiti (ABUAD)',
    'Bamidele Olumilua University of Education, Science & Technology, Ikere-Ekiti',
    'Ekiti State Polytechnic, Isan-Ekiti',
    'Federal Polytechnic, Ire',
    'Ekiti State College of Education, Ikole-Ekiti',
    'Ekiti State University College of Education, Ado-Ekiti',
  ],
  Enugu: [
    'University of Nigeria, Nsukka (UNN)',
    'Enugu State University of Science & Technology (ESUT)',
    'Godfrey Okoye University, Enugu',
    'Caritas University, Enugu',
    'Coal City University, Enugu',
    'Institute of Management and Technology (IMT), Enugu',
    'Enugu State Polytechnic, Enugu',
    'Federal Polytechnic, Onitsha',
    'College of Education, Enugu',
    'Federal College of Education, Enugu',
  ],
  'FCT (Abuja)': [
    'University of Abuja (UNIABUJA)',
    'Nile University of Nigeria, Abuja',
    'Baze University, Abuja',
    'Veritas University, Abuja',
    'African University of Science & Technology (AUST), Abuja',
    'Abubakar Ibrahim Tafawa Balewa University, Abuja',
    'Federal University of Technology, Minna (FUTMINNA)',
    'Federal College of Education, Zuba',
    'Federal College of Education, Abeokuta',
    'FCT College of Education, Abuja',
  ],
  Gombe: [
    'Federal University of Kashere, Gombe',
    'Gombe State University, Gombe',
    'Gombe State University of Science and Technology, Kumo',
    'Gombe State Polytechnic, Gombe',
    'Federal Polytechnic, Gombe',
    'Gombe State College of Education, Gombe',
    'Gombe College of Education, Bajoga',
  ],
  Imo: [
    'Imo State University, Owerri (IMSU)',
    'Federal University of Technology, Owerri (FUTO)',
    'Rhema University, Aba',
    'Imo State Polytechnic, Umuagwo',
    'Owerri Polytechnic',
    'Alvan Ikoku Federal College of Education, Owerri',
    'Federal College of Education (Technical), Omuma',
    'Imo State College of Education, Ihitte-Uboma',
  ],
  Jigawa: [
    'Sule Lamido University, Kafin Hausa',
    'Federal University, Dutse',
    'Jigawa State Polytechnic, Dutse',
    'Federal Polytechnic, Azare',
    'Jigawa State University, Kafin Hausa',
    'Jigawa State College of Education, Gumel',
    'Jigawa College of Education, Dutse',
  ],
  Kaduna: [
    'Ahmadu Bello University, Zaria (ABU)',
    'Kaduna State University (KASU), Kaduna',
    'Kaduna Polytechnic, Kaduna',
    'Nigerian Defence Academy (NDA), Kaduna',
    'Nuhu Bamalli Polytechnic, Zaria',
    'Kaduna State Polytechnic',
    'Federal College of Education, Zaria',
    'College of Education, Gidan Waya',
    'Kaduna State College of Education, Kafanchan',
  ],
  Kano: [
    'Bayero University, Kano (BUK)',
    'Kano University of Science & Technology, Wudil (KUST)',
    'Northwest University, Kano',
    'Kano State Polytechnic, Kano',
    'Federal Polytechnic, Kano',
    'Abubakar Tatanaki College of Education',
    'Kano State College of Education and Preliminary Studies (KACES)',
    'Federal College of Education (Technical), Bichi',
  ],
  Katsina: [
    'Federal University Dutsin-Ma, Katsina',
    "Umaru Musa Yar'Adua University, Katsina (UMYU)",
    'Hassan Usman Katsina Polytechnic, Katsina',
    'Federal Polytechnic, Katsina',
    'Katsina State Polytechnic',
    'Katsina State College of Education, Katsina',
    'Katsina College of Education, Daura',
  ],
  Kebbi: [
    'Kebbi State University of Science & Technology, Aliero (KSUSTA)',
    'Federal University Birnin Kebbi',
    'Kebbi State Polytechnic, Birnin Kebbi',
    'Federal Polytechnic, Kebbi',
    'Kebbi College of Education, Argungu',
    'Kebbi State College of Education, Birnin Kebbi',
  ],
  Kogi: [
    'Kogi State University, Anyigba',
    'Federal University Lokoja, Lokoja',
    'Confluence University of Science & Technology, Osara',
    'Kogi State Polytechnic, Lokoja',
    'Federal Polytechnic, Itakpe',
    'Kogi State College of Education, Ankpa',
    'College of Education, Idah',
  ],
  Kwara: [
    'University of Ilorin (UNILORIN)',
    'Kwara State University, Malete (KWASU)',
    'Al-Hikmah University, Ilorin',
    'Landmark University, Omu-Aran',
    'Kwara State Polytechnic, Ilorin',
    'Federal Polytechnic, Offa',
    'College of Education, Ilorin',
    'Kwara State College of Education, Oro',
  ],
  Lagos: [
    'University of Lagos (UNILAG), Lagos',
    'Lagos State University (LASU), Ojo',
    'Pan-Atlantic University, Ibeju-Lekki',
    'Caleb University, Lagos',
    'Lagos State University of Science and Technology (LASUSTECH), Ikorodu',
    'Yaba College of Technology (YABATECH), Lagos',
    'The Polytechnic, Lagos',
    'Lagos City University, Lagos',
    'Federal College of Education (Technical), Lagos',
    'College of Education, Agbado-Oke Aro',
  ],
  Nasarawa: [
    'Nasarawa State University, Keffi',
    'Federal University of Lafia, Lafia',
    'Nasarawa State Polytechnic, Lafia',
    'Federal Polytechnic, Nasarawa',
    'Nasarawa State Polytechnic, Keffi',
    'Nasarawa State College of Education, Akwanga',
    'College of Education, Lafia',
  ],
  Niger: [
    'Federal University of Technology, Minna (FUTMINNA)',
    'Ibrahim Badamasi Babangida University, Lapai',
    'Niger State University, Minna (NSUK)',
    'Niger State Polytechnic, Zungeru',
    'Federal Polytechnic, Bida',
    'Niger State College of Education, Minna',
    'Niger State College of Education, Bida',
  ],
  Ogun: [
    'Olabisi Onabanjo University, Ago-Iwoye (OOU)',
    'Babcock University, Ilishan-Remo',
    'Covenant University, Ota',
    'Federal University of Agriculture, Abeokuta (FUNAAB)',
    'Tai Solarin University of Education, Ijebu-Ode',
    'Moshood Abiola Polytechnic, Abeokuta',
    'Ogun State Polytechnic, Abeokuta',
    'Federal Polytechnic, Ilaro',
    'Ogun State College of Education, Abeokuta',
    'College of Education, Ijebu-Ode',
  ],
  Ondo: [
    'Federal University of Technology, Akure (FUTA)',
    'Adekunle Ajasin University, Akungba-Akoko (AAUA)',
    'Elizade University, Ilara-Mokin',
    'Achievers University, Owo',
    'Ondo State University, Ondo',
    'Ondo State Polytechnic, Owo',
    'Federal Polytechnic, Ilaro',
    'Ondo State College of Education, Akure',
    'Ondo College of Education, Ilesha-Baruba',
  ],
  Osun: [
    'Obafemi Awolowo University, Ile-Ife (OAU)',
    'Osun State University, Osogbo (UNIOSUN)',
    'Adeleke University, Ede',
    "Redeemer's University, Ede",
    'Osun State Polytechnic, Iree',
    'Federal Polytechnic, Ilesa',
    'Osun College of Education',
    'Federal College of Education, Osun',
  ],
  Oyo: [
    'University of Ibadan (UI)',
    'Ladoke Akintola University of Technology, Ogbomoso (LAUTECH)',
    'Lead City University, Ibadan',
    'The Polytechnic, Ibadan',
    'Emmanuel Alayande University of Education, Oyo',
    'Oyo State Polytechnic, Ibadan',
    'Federal Polytechnic, Oyo',
    'Oyo State College of Education, Oyo',
    'College of Education, Lanlate',
  ],
  Plateau: [
    'University of Jos (UNIJOS)',
    'Plateau State University, Bokkos',
    'Plateau State Polytechnic, Barkin Ladi',
    'Federal Polytechnic, Jos',
    'Plateau State Polytechnic',
    'Plateau State College of Education, Jos',
    'Federal College of Education, Pankshin',
  ],
  Rivers: [
    'University of Port Harcourt (UNIPORT)',
    'Rivers State University, Port Harcourt (RSU)',
    'Ignatius Ajuru University of Education, Port Harcourt',
    'Captain Elechi Amadi Polytechnic, Port Harcourt',
    'Rivers State Polytechnic, Bori',
    'Federal Polytechnic, Orogun',
    'College of Education, Port Harcourt',
    'Rivers State College of Education, Rumueme',
  ],
  Sokoto: [
    'Usmanu Danfodiyo University, Sokoto (UDUS)',
    'Sokoto State University, Sokoto',
    'Sokoto State Polytechnic, Sokoto',
    'Federal Polytechnic, Sokoto',
    'Sokoto State College of Education, Sokoto',
    'College of Education, Gusau (Zamfara)',
  ],
  Taraba: [
    'Taraba State University, Jalingo',
    'Federal University Wukari, Wukari',
    'Taraba State Polytechnic, Suntai',
    'Federal Polytechnic, Taraba',
    'Taraba College of Education, Jalingo',
    'College of Education, Zing',
  ],
  Yobe: [
    'Federal University Gashua, Gashua',
    'Yobe State University, Damaturu',
    'Yobe State Polytechnic, Damaturu',
    'Federal Polytechnic, Gashua',
    'Yobe State College of Education, Gashua',
    'Yobe College of Education, Damaturu',
  ],
  Zamfara: [
    'Federal University Gusau, Gusau',
    'Zamfara State University, Talata Mafara',
    'Zamfara State College of Education, Maru',
    'Zamfara State Polytechnic, Gusau',
    'Federal Polytechnic, Kaura-Namoda',
    'Zamfara College of Education, Talata Mafara',
  ],
}
