export const NIGERIA_STATES = [
  'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa',
  'Benue', 'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo',
  'Ekiti', 'Enugu', 'FCT (Abuja)', 'Gombe', 'Imo', 'Jigawa',
  'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara',
  'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun',
  'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara',
] as const

export type NigeriaState = (typeof NIGERIA_STATES)[number]

export const INSTITUTIONS_BY_STATE: Record<string, string[]> = {
  Abia: [
    'Abia State University (ABSU), Uturu',
    'Michael Okpara University of Agriculture, Umudike',
    'Gregory University, Uturu',
    'Abia State Polytechnic, Aba',
  ],
  Adamawa: [
    'Modibbo Adama University, Yola',
    'Adamawa State University, Mubi',
    'American University of Nigeria, Yola',
    'Adamawa State Polytechnic, Yola',
  ],
  'Akwa Ibom': [
    'University of Uyo (UNIUYO)',
    'Akwa Ibom State University, Ikot Akpaden',
    'Ritman University, Ikot Ekpene',
    'Heritage Polytechnic, Eket',
  ],
  Anambra: [
    'Nnamdi Azikiwe University (UNIZIK), Awka',
    'Chukwuemeka Odumegwu Ojukwu University (COOU)',
    'Paul University, Awka',
    'Madonna University, Okija',
    'Anambra State Polytechnic, Mgbakwu',
  ],
  Bauchi: [
    'Abubakar Tafawa Balewa University (ATBU), Bauchi',
    'Bauchi State University, Gadau',
    'Bauchi State Polytechnic',
  ],
  Bayelsa: [
    'Niger Delta University, Wilberforce Island',
    'Federal University, Otuoke',
    'Isaac Jasper Boro College of Education, Sagbama',
  ],
  Benue: [
    'Joseph Sarwuan Tarka University, Makurdi (JOSTUM)',
    'Benue State University, Makurdi',
    'Federal University of Agriculture, Makurdi (FUAM)',
    'Benue State Polytechnic, Ugbokolo',
  ],
  Borno: [
    'University of Maiduguri (UNIMAID)',
    'Borno State University, Maiduguri',
    'Ramat Polytechnic, Maiduguri',
  ],
  'Cross River': [
    'University of Calabar (UNICAL)',
    'Cross River University of Technology (CRUTECH)',
    'Arthur Jarvis University, Akpabuyo',
  ],
  Delta: [
    'Delta State University, Abraka (DELSU)',
    'Federal University of Petroleum Resources, Effurun (FUPRE)',
    'University of Delta, Agbor',
    'Dennis Osadebay University, Asaba',
    'Delta State Polytechnic, Ogwashi-Uku',
  ],
  Ebonyi: [
    'Ebonyi State University, Abakaliki (EBSU)',
    'Alex Ekwueme Federal University, Ndufu-Alike (FUNAI)',
    'David Umahi Federal University of Health Sciences',
  ],
  Edo: [
    'University of Benin (UNIBEN)',
    'Ambrose Alli University, Ekpoma (AAU)',
    'Benson Idahosa University, Benin City',
    'Igbinedion University, Okada',
    'Wellspring University, Benin City',
  ],
  Ekiti: [
    'Ekiti State University (EKSU), Ado-Ekiti',
    'Federal University Oye-Ekiti (FUOYE)',
    'Afe Babalola University, Ado-Ekiti (ABUAD)',
    'Bamidele Olumilua University of Education, Science & Technology',
  ],
  Enugu: [
    'University of Nigeria, Nsukka (UNN)',
    'Enugu State University of Science & Technology (ESUT)',
    'Godfrey Okoye University, Enugu',
    'Caritas University, Enugu',
    'Coal City University, Enugu',
  ],
  'FCT (Abuja)': [
    'University of Abuja (UNIABUJA)',
    'Nile University of Nigeria, Abuja',
    'Baze University, Abuja',
    'Veritas University, Abuja',
    'African University of Science & Technology (AUST)',
  ],
  Gombe: [
    'Federal University of Kashere, Gombe',
    'Gombe State University',
    'Gombe State University of Science and Technology, Kumo',
  ],
  Imo: [
    'Imo State University, Owerri (IMSU)',
    'Federal University of Technology, Owerri (FUTO)',
    'Rhema University, Aba',
    'Imo State Polytechnic, Umuagwo',
  ],
  Jigawa: [
    'Sule Lamido University, Kafin Hausa',
    'Federal University, Dutse',
    'Jigawa State Polytechnic, Dutse',
  ],
  Kaduna: [
    'Ahmadu Bello University, Zaria (ABU)',
    'Kaduna State University (KASU)',
    'Kaduna Polytechnic',
    'Nigerian Defence Academy (NDA)',
  ],
  Kano: [
    'Bayero University, Kano (BUK)',
    'Kano University of Science & Technology, Wudil (KUST)',
    'Northwest University, Kano',
    'Kano State Polytechnic',
  ],
  Katsina: [
    'Federal University Dutsin-Ma, Katsina',
    "Umaru Musa Yar'Adua University, Katsina (UMYU)",
    'Hassan Usman Katsina Polytechnic',
  ],
  Kebbi: [
    'Kebbi State University of Science & Technology, Aliero (KSUSTA)',
    'Federal University Birnin Kebbi',
    'Kebbi State Polytechnic',
  ],
  Kogi: [
    'Kogi State University, Anyigba',
    'Federal University Lokoja',
    'Confluence University of Science & Technology, Osara',
  ],
  Kwara: [
    'University of Ilorin (UNILORIN)',
    'Kwara State University, Malete (KWASU)',
    'Al-Hikmah University, Ilorin',
    'Landmark University, Omu-Aran',
    'Kwara State Polytechnic, Ilorin',
  ],
  Lagos: [
    'University of Lagos (UNILAG)',
    'Lagos State University (LASU), Ojo',
    'Pan-Atlantic University, Ibeju-Lekki',
    'Caleb University, Lagos',
    'Lagos State University of Science and Technology (LASUSTECH)',
    'Yaba College of Technology (YABATECH)',
  ],
  Nasarawa: [
    'Nasarawa State University, Keffi',
    'Federal University of Lafia',
    'Nasarawa State Polytechnic, Lafia',
  ],
  Niger: [
    'Federal University of Technology, Minna (FUTMINNA)',
    'Ibrahim Badamasi Babangida University, Lapai',
    'Niger State University, Minna (NSUK)',
    'Niger State Polytechnic, Zungeru',
  ],
  Ogun: [
    'Olabisi Onabanjo University, Ago-Iwoye (OOU)',
    'Babcock University, Ilishan-Remo',
    'Covenant University, Ota',
    'Federal University of Agriculture, Abeokuta (FUNAAB)',
    'Tai Solarin University of Education, Ijebu-Ode',
    'Moshood Abiola Polytechnic, Abeokuta',
  ],
  Ondo: [
    'Federal University of Technology, Akure (FUTA)',
    'Adekunle Ajasin University, Akungba-Akoko (AAUA)',
    'Elizade University, Ilara-Mokin',
    'Achievers University, Owo',
  ],
  Osun: [
    'Obafemi Awolowo University, Ile-Ife (OAU)',
    'Osun State University, Osogbo (UNIOSUN)',
    'Adeleke University, Ede',
    "Redeemer's University, Ede",
  ],
  Oyo: [
    'University of Ibadan (UI)',
    'Ladoke Akintola University of Technology, Ogbomoso (LAUTECH)',
    'Lead City University, Ibadan',
    'The Polytechnic, Ibadan',
    'Emmanuel Alayande University of Education',
  ],
  Plateau: [
    'University of Jos (UNIJOS)',
    'Plateau State University, Bokkos',
    'Plateau State Polytechnic, Barkin Ladi',
  ],
  Rivers: [
    'University of Port Harcourt (UNIPORT)',
    'Rivers State University, Port Harcourt (RSU)',
    'Ignatius Ajuru University of Education, Port Harcourt',
    'Captain Elechi Amadi Polytechnic, Port Harcourt',
  ],
  Sokoto: [
    'Usmanu Danfodiyo University, Sokoto (UDUS)',
    'Sokoto State University',
    'Sokoto State Polytechnic',
  ],
  Taraba: [
    'Taraba State University, Jalingo',
    'Federal University Wukari',
    'Taraba State Polytechnic, Suntai',
  ],
  Yobe: [
    'Federal University Gashua',
    'Yobe State University, Damaturu',
  ],
  Zamfara: [
    'Federal University Gusau',
    'Zamfara State University, Talata Mafara',
    'Zamfara State College of Education, Maru',
  ],
}
